### ISSUE TITLE
How to disable the mpi during the installation.

### ISSUE THREAD

**Issue by ztdepztdep** [chiao45/mgmetis#8]
I have installed it successfully, but wheni run it. it feeds back the following error:
   `OSError: libmpi.so.20: cannot open shared object file: No such file or directory`

**Comment by chiao45** [comment]
Hi, @ztdepztdep. I think this somehow relates to the `mpi4py` installation (or, in particular, your MPI installation); see https://bitbucket.org/mpi4py/mpi4py/issues/134/install-issue-libmpiso20-cannot-open for some hints regarding how to debug `mpi4py`. Meanwhile, I agree with you that it is better to allow users to manually disable parmetis in the installation process via some environment variables (or something else, I will think about this).

I will work on this when I have some spare time. As a temporary workaround, you can install from the source and manually set `mpi4py=None` in `conf.py` (hope this works)...
